<?php
/**
 * BcauthorizeTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Mtn\Momo\Disbursement
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Disbursements
 *
 * Automatically deposit funds to multiple users
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Mtn\Momo\Disbursement\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * BcauthorizeTest Class Doc Comment
 *
 * @category    Class
 * @description Bcauthorize
 * @package     Mtn\Momo\Disbursement
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class BcauthorizeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Bcauthorize"
     */
    public function testBcauthorize()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "scope"
     */
    public function testPropertyScope()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "login_hint"
     */
    public function testPropertyLoginHint()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "access_type"
     */
    public function testPropertyAccessType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "consent_valid_in"
     */
    public function testPropertyConsentValidIn()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "client_notification_token"
     */
    public function testPropertyClientNotificationToken()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "scope_instruction"
     */
    public function testPropertyScopeInstruction()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
