<?php
/**
 * DeliverynotificationTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Mtn\Momo\Disbursement
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Disbursements
 *
 * Automatically deposit funds to multiple users
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Mtn\Momo\Disbursement\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * DeliverynotificationTest Class Doc Comment
 *
 * @category    Class
 * @description Deliverynotification
 * @package     Mtn\Momo\Disbursement
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DeliverynotificationTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Deliverynotification"
     */
    public function testDeliverynotification()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "notification_message"
     */
    public function testPropertyNotificationMessage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
