<?php
/**
 * DefaultApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Mtn\Momo\Disbursement
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Disbursements
 *
 * Automatically deposit funds to multiple users
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Mtn\Momo\Disbursement\Test\Api;

use \Mtn\Momo\Disbursement\Configuration;
use \Mtn\Momo\Disbursement\ApiException;
use \Mtn\Momo\Disbursement\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Mtn\Momo\Disbursement
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DefaultApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for bcAuthorize
     *
     * bc-authorize.
     *
     */
    public function testBcAuthorize()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createAccessToken
     *
     * CreateAccessToken.
     *
     */
    public function testCreateAccessToken()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createOauth2Token
     *
     * CreateOauth2Token.
     *
     */
    public function testCreateOauth2Token()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for depositV1
     *
     * Deposit-V1.
     *
     */
    public function testDepositV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for depositV2
     *
     * Deposit-V2.
     *
     */
    public function testDepositV2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAccountBalance
     *
     * GetAccountBalance.
     *
     */
    public function testGetAccountBalance()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAccountBalanceInSpecificCurrency
     *
     * GetAccountBalanceInSpecificCurrency.
     *
     */
    public function testGetAccountBalanceInSpecificCurrency()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getBasicUserinfo
     *
     * GetBasicUserinfo.
     *
     */
    public function testGetBasicUserinfo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDepositStatus
     *
     * GetDepositStatus.
     *
     */
    public function testGetDepositStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRefundStatus
     *
     * GetRefundStatus.
     *
     */
    public function testGetRefundStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTransferStatus
     *
     * GetTransferStatus.
     *
     */
    public function testGetTransferStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getUserInfoWithConsent
     *
     * GetUserInfoWithConsent.
     *
     */
    public function testGetUserInfoWithConsent()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for refundV1
     *
     * Refund-V1.
     *
     */
    public function testRefundV1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for refundV2
     *
     * Refund-V2.
     *
     */
    public function testRefundV2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for transfer
     *
     * Transfer.
     *
     */
    public function testTransfer()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for validateAccountHolderStatus
     *
     * ValidateAccountHolderStatus.
     *
     */
    public function testValidateAccountHolderStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
